namespace: stackhpc
name: cloud_portal_tools
version: 0.1.0
description: Roles and playbooks for deploying tools onto hosts managed by the cloud portal.
readme: README.md
authors:
  - "Matt Pryor <matt@stackhpc.com>"
repository: https://github.com/stackhpc/ansible-collection-cloud-portal-tools

dependencies:
  ansible.posix: "*"
  containers.podman: "*"
