namespace: stackhpc
name: azimuth_tools
version: 0.1.0
description: Roles and playbooks for deploying tools onto hosts managed by the Azimuth portal.
readme: README.md
authors:
  - "Matt Pryor <matt@stackhpc.com>"
repository: https://github.com/stackhpc/ansible-collection-azimuth-tools

dependencies:
  ansible.posix: "*"
  containers.podman: "*"
