---

# Load the OpenStack metadata from the instance
_openstack_metadata: "{{ lookup('url', 'http://169.254.169.254/openstack/latest/meta_data.json') | from_json }}"

# Determine whether the desktop is enabled
guacamole_desktop_enabled: "{{ (_openstack_metadata.meta.portal_desktop_enabled | default('0')) == '1' }}"

# Get the Zenith client version, SSHD host/port and the subdomain to use from the metadata
zenith_client_image_tag: "{{ _openstack_metadata.meta.portal_apps_client_tag | default('main') }}"
zenith_client_sshd_host: "{{ _openstack_metadata.meta.portal_apps_sshd_host }}"
zenith_client_sshd_port: "{{ _openstack_metadata.meta.portal_apps_sshd_port }}"
zenith_client_subdomain: "{{ _openstack_metadata.meta.portal_apps_subdomain }}"
