---

#####
## Tasks to set up the VNC server for the guacamole user
#####

- name: Get guacamole user info
  user:
    name: "{{ guacamole_user }}"
    state: present
  register: guacamole_user_info

- name: Generate VNC server password for guacamole user
  command: openssl rand -hex 32
  changed_when: false
  register: guacamole_user_vnc_password_gen

- name: Set VNC server user facts for guacamole user
  set_fact:
    guacamole_user_vnc_config_dir: "{{ guacamole_user_info.home }}/.vnc"
    guacamole_user_vnc_password: "{{ guacamole_user_vnc_password_gen.stdout | trim }}"

- name: Ensure VNC user config directory exists
  file:
    path: "{{ guacamole_user_vnc_config_dir }}"
    state: directory
    owner: "{{ guacamole_user }}"

- name: Create VNC password file
  shell: echo "{{ guacamole_user_vnc_password }}" | vncpasswd -f > {{ guacamole_user_vnc_config_dir }}/passwd
  become: yes
  become_user: "{{ guacamole_user }}"

- name: Ensure permissions on VNC password file
  file:
    path: "{{ guacamole_user_vnc_config_dir }}/passwd"
    mode: "g=,o="

- name: Configure VNC server (RedHat)
  block:
    - name: Write VNC configuration
      copy:
        dest: "{{ guacamole_user_vnc_config_dir }}/config"
        content: |
          interface={{ guacamole_host_address }}
          localhost=no
          rfbauth={{ guacamole_user_vnc_config_dir }}/passwd
          session=gnome
          MaxCutText=99999999
      become: yes
      become_user: "{{ guacamole_user }}"

    - name: Add guacamole user to displays
      lineinfile:
        path: /etc/tigervnc/vncserver.users
        regexp: "^:1="
        line: ":1={{ guacamole_user }}"
        create: yes

    - name: Restore SELinux context for .vnc directory
      command: restorecon -RFv {{ guacamole_user_vnc_config_dir }}
  when: ansible_os_family == "RedHat"

- name: Configure VNC server (Ubuntu)
  block:
    # This file is run to start the Gnome session for the VNC server
    # - name: Install xstartup file
    #   copy:
    #     dest: "{{ guacamole_user_vnc_config_dir }}/xstartup"
    #     content: |
    #       #!/bin/bash
    #       PATH=/usr/bin:/usr/sbin
    #       unset SESSION_MANAGER
    #       unset DBUS_SESSION_BUS_ADDRESS
    #       exec /usr/bin/gnome-session --session=gnome
    #     owner: "{{ guacamole_user }}"
    #     group: "{{ guacamole_user }}"
    #     mode: "+x"

    - name: Ensure systemd overrides directory exists
      file:
        path: /etc/systemd/system/vncserver@:1.service.d
        state: directory

    - name: Configure guacamole as user for systemd unit
      template:
        src: vncserver-user.conf
        dest: /etc/systemd/system/vncserver@:1.service.d/user.conf

    - name: Reload systemd units
      systemd:
        daemon_reload: yes
  when: ansible_os_family != "RedHat"

- name: Start VNC server for guacamole user
  service:
    name: vncserver@:1
    state: started
    enabled: yes
