---

- name: Install and start tunnel proxy
  include_role:
    name: podman
    tasks_from: install-systemd-unit
  vars:
    podman_service_name: "{{ tunnel_proxy_name }}"
    podman_service_type: container
    podman_service_image: "{{ tunnel_proxy_image }}"
    podman_service_pod: "{{ tunnel_proxy_pod }}"
    podman_service_wants: "{{ tunnel_proxy_wants }}"
    # Join the default and extra variables to get the environment
    podman_service_env: "{{ tunnel_proxy_environment_default | combine(tunnel_proxy_environment) }}"
