---

- hosts: all
  become: yes
  collections:
    - stackhpc.azimuth_tools
  pre_tasks:
    # Include the variables for the OS distribution we are running on
    # Note that we don't use first_found across the whole list of files because
    # we want to include all the ones that apply, in the order in which they are defined
    # However we do use first_found to handle the case where the file doesn't exist at all
    - name: Include dynamic variables
      include_vars: "{{ vars_file }}"
      vars:
        vars_file: "{{ lookup('first_found', lookup_params) }}"
        lookup_params:
          files: ["{{ item }}"]
          skip: true
      when: vars_file
      loop:
        - "{{ playbook_dir }}/vars/openstack.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  roles:
    - guacamole
    - role: zenith-client
      vars:
        zenith_client_name: guacamole-zenith-client
        # Join the guacamole pod to access the guacamole client on localhost
        zenith_client_pod: guacamole
        # Use a soft dependency on the mitm
        zenith_client_wants:
          - guacamole-mitm
        # Forward traffic to the MITM proxy
        zenith_client_forward_to_host: localhost
        zenith_client_forward_to_port: "8081"
