---

- hosts: all
  become: yes
  collections:
    - stackhpc.cloud_portal_tools
  pre_tasks:
    # Include the variables for the OS distribution we are running on
    # Note that we don't use first_found across the whole list of files because
    # we want to include all the ones that apply, in the order in which they are defined
    # However we do use first_found to handle the case where the file doesn't exist at all
    - name: Include dynamic variables
      include_vars: "{{ task_file }}"
      vars:
        task_file: "{{ lookup('first_found', lookup_params) }}"
        lookup_params:
          files: ["{{ item }}"]
          skip: true
      when: task_file
      loop:
        - vars/openstack.yml
        - vars/{{ ansible_os_family }}.yml
        - vars/{{ ansible_distribution }}.yml
        - vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml
  roles:
    - guacamole
    - role: tunnel-proxy
      vars:
        tunnel_proxy_name: guacamole-proxy
        # Join the guacamole pod to access the guacamole client on localhost
        tunnel_proxy_pod: guacamole
        # Use a soft dependency on the client
        tunnel_proxy_wants:
          - guacamole-client
        tunnel_proxy_forward_to_host: localhost
        tunnel_proxy_forward_to_port: "8080"
        tunnel_proxy_service_name: console
