---

podman_service_type: container
podman_service_wants: []
podman_service_ports: []
podman_service_env: {}
podman_service_volumes: []
podman_service_user: "{{ ansible_user }}"
podman_service_group: "{{ podman_service_user }}"
podman_service_restart: no
