name: Publish artifacts
# Run the tasks on every push
on: push
jobs:
  build_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate metadata for image
        id: image-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/stackhpc/azimuth-guacamole-mitm
          # Produce the branch name or tag and the SHA as tags
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=

      - name: Build and push image
        uses: stackhpc/github-actions/docker-multiarch-build-push@master
        with:
          cache-key: guacamole-mitm
          context: ./images/guacamole-mitm
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-meta.outputs.tags }}
          labels: ${{ steps.image-meta.outputs.labels }}
